### ISSUE TITLE
2 gamepads = crash

### ISSUE THREAD

**Issue by BeWorld2018** [jacadcaps/gamepadlib#1]
Hi,

I test quickly gamepadlib-test project in debug mode , when i put put 2 joystick i have a crash.
Maybe it's not finish.
If i can help or more test, tell me.
Thanks

`MorphOS ID 3.13 (6.2.2020)
saved: 2020 06 25 18:52

[20200625 18:51:52] >>> Exception 4 <Illegal Inst Access at 00281c94>
----------------------------------------------------------------------
  Quark Thread TID 0000000010020010 Name ABox
   SRR0 0x00281c94 SRR1 0x4200f030
     LR 0x190aeb18  CTR 0x00281c96
     CR 0x22002242  XER 0x00000400
GPR[00] 190aeab8 1c97d830 1c97e240 190e7860 00000000 1c97d838 190d4950 00000001
GPR[08] 00000002 80200007 802003ec 14001948 48002444 00000000 00000000 00000000
GPR[16] 00000000 00000000 190c8a7c 190c7dfc 190c8a78 00000001 06431f7f 190c8a78
GPR[24] 00000c80 06436a7c 1c383bcc 18eb0000 00000000 00000000 18eb0000 1bb9afd8
  FPSCR 82020000
FPR[00] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[04] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[08] 0000000000000000 0000000000000000 0000000000000000 41f0000000000000
FPR[12] 4330000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[16] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[20] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[24] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[28] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
  VSAVE 00000000        VSCR 00010000
VPR[00] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[02] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[04] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[06] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[08] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[10] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[12] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[14] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[16] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[18] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[20] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[22] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[24] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[26] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[28] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[30] 00000000000000000000000000000000 00000000000000000000000000000000
   IABR 00000000
   DABR 00000000
  MMCR0 00000000
  MMCR1 00000000
  MMCR2 00000000
   PMC1 00000000 PMC2 00000000 PMC3 00000000 PMC4 00000000
    SIA 00000000
    SDA 00000000
>>> Quark Thread Stack History
----------------------------------------------------------------------
StackFrame[ 0].LR[0x190ad268] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x00000848]
StackFrame[ 1].LR[0x190acf6c] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x0000054c]
StackFrame[ 2].LR[0x190acdb4] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x00000394]
StackFrame[ 3].LR[0x190acccc] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x000002ac]
StackFrame[ 4].LR[0x102ac628] -> dos.elf [Hunk 0 Offset 0x0001a968]
StackFrame[ 5].LR[0x102b2600] -> dos.elf [Hunk 0 Offset 0x00020940]
StackFrame[ 6].LR[0x102b2244] -> dos.elf [Hunk 0 Offset 0x00020584 Function RunCommand]
StackFrame[ 7].LR[0x103361a8] -> shell.elf [Hunk 0 Offset 0x000058a8]
StackFrame[ 8].LR[0x10331e88] -> shell.elf [Hunk 0 Offset 0x00001588]
StackFrame[ 9].LR[0x10330f70] -> shell.elf [Hunk 0 Offset 0x00000670]
StackFrame[10].LR[0x10330938] -> shell.elf [Hunk 0 Offset 0x00000038]
StackFrame[11].LR[0x102a17c8] -> dos.elf [Hunk 0 Offset 0x0000fb08]
StackFrame[12].LR[0x102a15f0] -> dos.elf [Hunk 0 Offset 0x0000f930]
StackFrame[13].LR[0x102a18bc] -> dos.elf [Hunk 0 Offset 0x0000fbfc]
>>> ABox State
----------------------------------------------------------------------
ExecBase: SysBase 0x14001948
       SysFlags 0x8000        AttnResched 0x0000        IDNestCnt -1 TDNestCnt -1
       ThisTask 0x190c7d18      TaskReady 0x168ad4e0     TaskWait 0x140243b0
     ResModules 0x140040e8
   TaskTrapCode 0x10120de4 TaskExceptCode 0x10120dec TaskExitCode 0x10120e48
   TaskSigAlloc 0xffff TaskTrapAlloc 0x8000
      IdleCount 293254 DispCount 2582896
        Quantum 4 Elapsed 4
VBlankFrequency 50 PowerSupplyFrequency 50 EClockFrequency 709379
        MainTID 0x10020010 SchedulerTID 0x10020012 SchedulerSig 0x80000000
        OldSRR0 0x0
ConfigServerTID 0x10000013
  LastIntObject 0x14128fcc
  LastIntObject 0x14128fcc <Not Valid ptr>
                 Code 0x1046b918 Data 0x14094548
           Int0: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int1: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int2: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int3: iv_Code 0x101262b8 iv_Data 0x14003b40 iv_Node 0x00000000
           Int4: iv_Code 0x101262b8 iv_Data 0x14003b60 iv_Node 0x00000000
           Int5: iv_Code 0x101262b8 iv_Data 0x14003b50 iv_Node 0x00000000
            Interrupt 0x1402e476 <graphics.library>
                 Code 0x1018dbe8 Data 0x1402e42c
            Interrupt 0x148ebe48 <ixemul timer interrupt>
                 Code 0x148e8f30 Data 0x00000000
           Int6: iv_Code 0x1018dbf0 iv_Data 0x1402e42c iv_Node 0x1402e4a2
           Int7: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int8: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int9: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int10: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int11: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int12: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int13: iv_Code 0x101262b8 iv_Data 0x14003b70 iv_Node 0x00000000
           Int14: iv_Code 0x00000000 iv_Data 0x00000000 iv_Node 0x00000000
           Int15: iv_Code 0x101262b8 iv_Data 0x14003b80 iv_Node 0x00000000

>>> Running Task
----------------------------------------------------------------------
      Task 0x190c7d18 Name 0x190c8a7c <Background CLI> Type 13 Pri 0
     Flags 0x8 State 2 IDNestCnt -1 TDNestCnt -1
  SigAlloc 0x8000ffff    SigWait 0x00000100 SigRecvd 0x80000100 SigExcept 0x00000000
ExceptCode 0x10120dec ExceptData 0x00000000 TrapCode 0x10120de4  TrapData 0x00000000
    Switch 0x00000000     Launch 0x00000000 UserData 0x00000000
   SPLower 0x1c97e35c    SPUpper 0x1c98635c    SPReg 0x190c8a18
----------------------------------------------------------------------
         ETask 0x1c389bf4
       MemPool 0x190dbd78     PPCLibData 0x00000000
    PPCSPLower 0x1c976334     PPCSPUpper 0x1c97e330
PPCTrapMsgPort 0x00000000 PPCTrapMessage 0x190c8a9c
   PPCRegFrame 0x1c97de50
     Private[] 0x00000000 0x00000000 0x00000000 0x00000000
    EmulHandle 0x00000000
----------------------------------------------------------------------
 EmulHandle 0x1c97e240     Type 0x00000004    Flags 0x00000001
SuperHandle 0x10001000     Type 0x00000000 WaitMask 0x00000000 SyncMask 0x00000000
        USP 0x00000000      SSP 0x140037a0      VBR 0x1400e238
        SFC 0x00000000      DFC 0x00000000     CACR 0xa0808000   TC 0x00000000
       ITT0 0x00000000     ITT1 0x00000000     DTT0 0x00000000 DTT1 0x00000000
        URP 0x00000000      SRP 0x00000000    BUSCR 0x00000000  PCR 0x04310501
>>> Task Registers Frame
----------------------------------------------------------------------
   SRR0 0x00281c94 SRR1 0x4200f030
     LR 0x190aeb18  CTR 0x00281c96
     CR 0x22002242  XER 0x00000400
GPR[00] 190aeab8 1c97d830 1c97e240 190e7860 00000000 1c97d838 190d4950 00000001
GPR[08] 00000002 80200007 802003ec 14001948 48002444 00000000 00000000 00000000
GPR[16] 00000000 00000000 190c8a7c 190c7dfc 190c8a78 00000001 06431f7f 190c8a78
GPR[24] 00000c80 06436a7c 1c383bcc 18eb0000 00000000 00000000 18eb0000 1bb9afd8
  FPSCR 82020000
FPR[00] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[04] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[08] 0000000000000000 0000000000000000 0000000000000000 41f0000000000000
FPR[12] 4330000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[16] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[20] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[24] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[28] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
  VSAVE 00000000        VSCR 00010000
VPR[00] 1133af6a000000080000000178300000 11330000000000001a1a1a1a1b1b1b1b
VPR[02] 1c1c1c1c1d1d1d1d1e1e1e1e1f1f1f1f 1000d97000044e381e1e1e1e0000000d
VPR[04] 102a18bc11393d91000000000000fbfc 1133af081133af081a1a1a1a1b1b1b1b
VPR[06] 1000d9301d1d1d1d14001b5c1133ae58 1000d93000044e380000000000000000
VPR[08] 1c1c1c1c1d1d1d1d1e1e1e1e1f1f1f1f 1000d97011006c9c11393d9100000000
VPR[10] 102a18bc1000d9781000d97c1000d980 1000d9601000d9780000000000000030
VPR[12] 1000d9700001182c1000d8d800000000 1000d98000044f580000000000000000
VPR[14] 1000d9c0000457042004288413131313 1000d9a0151515151000d9f00000000a
VPR[16] 1000d9b00001182c1e1e1e1e0000000a 1000d9c00001182c1000d9f000000000
VPR[18] 1000d9d000044f58000000001000dad0 1000da5000045fe80000000178300000
VPR[20] 00000000000000000000000000000000 30003000336238300000000000000000
VPR[22] 00000000000000000000000000000000 1133ae1c000000000000000000000000
VPR[24] 113390c8000000001a1a1a1a1b1b1b1b 1c1c1c1c1d1d1d1d1a1a1a1a1b1b1b1b
VPR[26] 1c1c1c1c1d1d1d1d1e1e1e1e1f1f1f1f 1000daf000044e380000000000000000
VPR[28] 0000000100b520080000000a000017a6 11339aa800b53bc30000000000000000
VPR[30] 00000000000000000000000000000000 00000000000000000000000000000000
>>> Task Stack History
----------------------------------------------------------------------
  LR[0x190aeb18] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x000020f8]
StackFrame[ 0].LR[0x190ad268] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x00000848]
StackFrame[ 1].LR[0x190acf6c] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x0000054c]
StackFrame[ 2].LR[0x190acdb4] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x00000394]
StackFrame[ 3].LR[0x190acccc] -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x000002ac]
StackFrame[ 4].LR[0x102ac628] -> dos.elf [Hunk 0 Offset 0x0001a968]
StackFrame[ 5].LR[0x102b2600] -> dos.elf [Hunk 0 Offset 0x00020940]
StackFrame[ 6].LR[0x102b2244] -> dos.elf [Hunk 0 Offset 0x00020584 Function RunCommand]
StackFrame[ 7].LR[0x103361a8] -> shell.elf [Hunk 0 Offset 0x000058a8]
StackFrame[ 8].LR[0x10331e88] -> shell.elf [Hunk 0 Offset 0x00001588]
StackFrame[ 9].LR[0x10330f70] -> shell.elf [Hunk 0 Offset 0x00000670]
StackFrame[10].LR[0x10330938] -> shell.elf [Hunk 0 Offset 0x00000038]
StackFrame[11].LR[0x102a17c8] -> dos.elf [Hunk 0 Offset 0x0000fb08]
StackFrame[12].LR[0x102a15f0] -> dos.elf [Hunk 0 Offset 0x0000f930]
StackFrame[13].LR[0x102a18bc] -> dos.elf [Hunk 0 Offset 0x0000fbfc]
Stack: 0x1c97d830
0x1c97d810[-0x20] 1c97d830 48002444 1c383bcc 18eb0000
0x1c97d820[-0x10] 1bb9afd8 00000000 18eb0000 1bb9afd8
0x1c97d830[0x000] 1c97d870 190aeab8 802003e9 190d4950
0x1c97d840[0x010] 802003ec 00000001 80200007 00000002
0x190aeab8 -> Work:dev/gamepadlib-master/gamepadlib-test [Hunk 1 Offset 0x00002098]
>>> Full PPC mode: Last saved 68k context
----------------------------------------------------------------------
   PC 87654321 SR 0008
Dn[0] 0000000e 00010001 1c9bc834 00000025 14001948 190c7d18 14001948 1c97d650
An[0] 14c01380 190daba8 0200f030 00000000 00000000 14023450 14001948 1c986354
Stack: 0x1c986354
0x1c986334[-0x20] e2c1ab7a c8b71a8f f19e2cd7 e771068f
0x1c986344[-0x10] 779fd279 7b96b625 9e2ff45c 1133e218
0x1c986354[0x000] 00008000 190c8a78 56a66d83 1c97e338
0x1c986364[0x010] 00004091 14000034 14000034 5e739276
0x1c986374[0x020] 47d90027 e25653e6 be496ab9 b96fd2f4
0x1c986384[0x030] 69fd59cb 9cdd3a31 5a08be50 13169b27
0x1c986394[0x040] e8a98325 72ee0dbd d3e553b5 9e6b9a5e
0x1c9863a4[0x050] eb434fd8 930eaa9e 21b1150e d5a071c6
0x1c9863b4[0x060] 060eb558 aa616860 8fb1230e 11f6e0dd
0x1c9863c4[0x070] b5f45d0f 1d254098 18fff5fd 3d6f584d
0x150ed5a0 -> MOSSYS:Ambient/Ambient [Hunk 1 Offset 0x0009acc8]
>>> Last saved PPCThread State
----------------------------------------------------------------------
   SRR0 0x1011ff18 SRR1 0x0200f030
     LR 0x1010f074  CTR 0x00000000
     CR 0x82004889  XER 0x00000000
GPR[00] 00000000 1c97d9f0 1c97e240 00000000 00000000 00000000 00000000 00000000
GPR[08] 00000000 00000000 00000000 00000000 00000000 00000000 80000004 00000001
GPR[16] 00000000 00000000 00000014 1c97dce4 00000002 00000000 190c7d18 11008ab0
GPR[24] 11008930 00000000 14023450 0725f628 00000005 1466d958 1466d9b4 14001948
  FPSCR 82020000
FPR[00] fff8000000fe502a 0000000000000000 0000000000000000 0000000000000000
FPR[04] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[08] 0000000000000000 0000000000000000 0000000000000000 41f0000000000000
FPR[12] 4330000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[16] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[20] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[24] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
FPR[28] 0000000000000000 0000000000000000 0000000000000000 0000000000000000
  VSAVE 00000000        VSCR 00010000
VPR[00] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[02] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[04] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[06] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[08] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[10] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[12] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[14] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[16] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[18] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[20] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[22] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[24] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[26] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[28] 00000000000000000000000000000000 00000000000000000000000000000000
VPR[30] 00000000000000000000000000000000 00000000000000000000000000000000
SRR0[0x1011ff18] -> exec_of_604e.elf [Hunk 0 Offset 0x0001ff18]
  LR[0x1010f074] -> exec_of_604e.elf [Hunk 0 Offset 0x0000f074 Function Reschedule]
StackFrame[ 0].LR[0x14023450]
StackFrame[ 1].LR[0x102b2600] -> dos.elf [Hunk 0 Offset 0x00020940]
StackFrame[ 2].LR[0x102b2244] -> dos.elf [Hunk 0 Offset 0x00020584 Function RunCommand]
StackFrame[ 3].LR[0x103361a8] -> shell.elf [Hunk 0 Offset 0x000058a8]
StackFrame[ 4].LR[0x10331e88] -> shell.elf [Hunk 0 Offset 0x00001588]
StackFrame[ 5].LR[0x10330f70] -> shell.elf [Hunk 0 Offset 0x00000670]
StackFrame[ 6].LR[0x10330938] -> shell.elf [Hunk 0 Offset 0x00000038]
StackFrame[ 7].LR[0x102a17c8] -> dos.elf [Hunk 0 Offset 0x0000fb08]
StackFrame[ 8].LR[0x102a15f0] -> dos.elf [Hunk 0 Offset 0x0000f930]
StackFrame[ 9].LR[0x102a18bc] -> dos.elf [Hunk 0 Offset 0x0000fbfc]

----------------------------------------------------------------------
    SegList 0x064323f8        GlobVec 0x1402356c
  StackBase 0x0725f8d7      StackSize 0x00008000
    TaskNum 0x00000004        Result2 0x00000000
 CurrentDir 0x06434966            CIS 0x070e1da3
        COS 0x06435d67            CES 0x0643bb63
ConsoleTask 0x1c38a5b0 FileSystemTask 0x140cbc3c
        CLI 0x070d2a8f     ReturnAddr 0x1c986354
    PktWait 0x00000000      WindowPtr 0x00000000
     HomeDir 0x0643234a         Flags 0x00000044
    ExitCode 0x00000000      ExitData 0x00000000
   Arguments 0x1c383bcc  ShellPrivate 0x00000000
CmdName: <Work:dev/gamepadlib-master/gamepadlib-test>
[20200625 18:51:52] >>> End of Exception State Dump
----------------------------------------------------------------------
`

**Comment by jacadcaps** [comment]
I will have a look tonight.
Meanwhile, I have most of the SDL2 integration code ready...

**Comment by BeWorld2018** [comment]
It's great new ! thanks you

**Comment by jacadcaps** [comment]
Hey, can you still reproduce this? If so, what gamepads did you use for testing? Can you provide a log with updated source tree? I haven't had the time to finish the SDL integration (it's half-done at the moment), but should be able to do so over the weekend. The latest commit adds support for HID gamepads and seems to work OK.

**Comment by BeWorld2018** [comment]
hi,

so, i recompile new version and test (debug) program. (Last SDK, MOS 3.13)

I have 4 games controllers to test : 
- A - Wireless Controller (xbox360.class), PS4 Dualshock
- B - Controller (xbox360.class), Xbox 360 Controller wired (rumble support) - Product 0x028E Vendor 0X045E
- C - XEOX GamePad (xbox360.class), speelink SL-6556-BK-V2 connected Xbox (rumble support)
- D - USB GamePad (hid.class), china gamepad 7$ :-) Product 0x0001 Vendro 2064

I. first test with 1 gamepag plugin : 
1) I connect only gamepad "B"
2) lauch test program
3) dont see any problem, i plug, unplug, test rumble etc.... working perfectly

II. second test
1) always gamepad 'B" is connected
2) launch progam test
3) i plug another gamepad "A"
4) crash.. no log in LogTool but i have box "LogServer" : 
![1](https://user-images.githubusercontent.com/36823759/86482247-df070000-bd51-11ea-9db0-b8a9f0c96ac3.png)

III. reboot and next test
1) i connect 2 gamepad "xbox360" A and B
2) launch program test
3) crash log
![2020-07-03_17h26_15](https://user-images.githubusercontent.com/36823759/86482480-5046b300-bd52-11ea-855e-f5cf8d201e8d.png)
[morphos.log](https://github.com/jacadcaps/gamepadlib/files/4870400/morphos.log)

IV. reboot and next test
1) i connect 2 gamepad but 1 xbox360.claas and other hid.class (B and D)
2) launch prorgam test... no crash
3) i see debug only buttons from xbox360.class (maybe first gamepad)

V. reboot and next test
1) i connect only hid.class (D)
2) working fine, buttons detected
3) unplug an plugin... not buttons detected but if i CTRL-E, it's ok
4) plugin game B, no problem... 2 gamepads working
5) plugin gampad C.... crashlog....

**Comment by jacadcaps** [comment]
Interesting. I couldn't reproduce this here. I did change the project configuration for Flow Studio. See if that helps...

**Comment by BeWorld2018** [comment]
well no chance... crash when use more than 1 gamepad xbox360.class for sure, all other case, no problem.

I try on another machine (powerbook) with clean Morphos/SDK, same, when i plu 2 xbox360 (PS4 and XBox gamepad).... i have a crash.

You have something we don't have :-)

**Comment by jacadcaps** [comment]
Just pushed some extra debug and made it use kprintf. If you've got a minute, crash the test_DEBUG and attach the logs. I should be able to see some more then... 

Also, try compiling with gcc7, just to rule out a compiler issue.

**Comment by BeWorld2018** [comment]
[log.log](https://github.com/jacadcaps/gamepadlib/files/4894735/log.log)

ok, i put gcc7 in project.

My test is :
 1 game XBOX plug, launch test_debug and plug a new XEOX gamepad xbox360.class
i create a screenshot of Trident / Devices

![2020-07-09_07h35_28](https://user-images.githubusercontent.com/36823759/87001031-c74ad400-c1b6-11ea-98bf-a8ddcae46f90.png)

**Comment by jacadcaps** [comment]
Thanks for the log! I can see what the problem is now...

**Comment by jacadcaps** [comment]
Fixed.
